sensor:
# Template All Lights
  - platform: template
    sensors:
      current_lights_on:
        friendly_name: All Lights Currently On
        unit_of_measurement: 'On'
        value_template: >
          {% set total = 0 %}

          {% if is_state('light.fib_fgd212_woonkamer_spots', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.combikast', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.fib_fgd212_eetkamer', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.dressoir', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.broodkast', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.nachtkast_l', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.nachtkast_r', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.ledstrip_slaapkamer', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.fib_fgd212_keuken_plafond', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.keuken_leds', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.fib_fgd212_keuken_nis', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.hal', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.gateway_light_7811dcdae475', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.garage', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.bijkeuken_leds', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.tuin', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.terras', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('switch.fib_fgs223_voordeur', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('switch.fib_fgs223_carport', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('switch.fib_fgs223_achterdeur', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('switch.kerstboom', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('switch.kerstverlichting', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.kerstolijf', 'on') %}
            {% set total = total + 1 %}
          {% endif %}

          {{total}}

# Template All Devices
  - platform: template
    sensors:
      current_devices_on:
        friendly_name: All Devices Currently On
        unit_of_measurement: 'On'
        value_template: >
          {% set total = 0 %}

          {% if is_state('media_player.woonkamer', 'playing') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('media_player.tv_woonkamer', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('cover.slaapkamer', 'closed') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('media_player.tv_slaapkamer', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('media_player.boven', 'playing') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('switch.printer', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('input_select.afzuigkap_status', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('input_select.dishwasher_status', 'running') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('media_player.tuin', 'playing') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('input_select.washing_machine_status', 'running') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('input_select.dryer_status', 'running') %}
            {% set total = total + 1 %}
          {% endif %}

          {{total}}

# Template All Sensors
  - platform: template
    sensors:
      current_sensors_on:
        friendly_name: All Sensors Currently On
        unit_of_measurement: 'On'
        value_template: >
          {% set total = 0 %}

          {% if is_state('binary_sensor.contact_garagedeur', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('binary_sensor.contact_achterdeur', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('binary_sensor.contact_slaapkamerraam', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('binary_sensor.contact_kleine_kamerraam', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('binary_sensor.contact_logeerkamerraam', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('binary_sensor.contact_zolderraam', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('binary_sensor.motion_woonkamer', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('binary_sensor.motion_garage', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('binary_sensor.motion_slaapkamer', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('binary_sensor.fib_fgsd002_overloop_brandmelder', 'on') %}
            {% set total = total + 1 %}
          {% endif %}

          {{total}}