---
# The dsmr_reader sensor platform allows you to easily add all sensors that DSMR Reader exposes to MQTT.
# It adds a separate sensor for every field in the MQTT topics.
# https://www.home-assistant.io/integrations/dsmr_reader/
sensor:
  - platform: dsmr_reader

  - platform: template
    sensors:
      power_consumption_watt:
        friendly_name: "Power Consumption Watt"
        unit_of_measurement: "W"
        value_template: "{{ states('sensor.dsmr_reading_electricity_currently_delivered') | float * 1000 }}"


# https://www.home-assistant.io/components/utility_meter/
# utility_meter:
  # power_hourly:
  #   source: sensor.power_consumption_today
  #   cycle: hourly
  # gas_hourly:
  #   source: sensor.gas_verbruik_totaal
  #   cycle: hourly