sensor:
  # https://www.home-assistant.io/components/imap/
  # The imap sensor platform is observing your IMAP server and reporting the amount of unread emails.
  - platform: imap
    name: Mail Jeroen
    server: !secret mail_host_jeroen
    username: !secret mail_user_jeroen
    password: !secret mail_pass_jeroen
    port: 993
    charset: US-ASCII

  - platform: imap
    name: Mail Jeroen Werk
    server: !secret mail_host_jeroen_work
    username: !secret mail_user_jeroen_work
    password: !secret mail_pass_jeroen_work
    port: 993
    charset: US-ASCII