# OctoPrint is a web interface for your 3D printer.
# This is the main integration to integrate OctoPrint sensors.
# https://www.home-assistant.io/integrations/octoprint

# octoprint:
#   host: !secret octoprint_host
#   api_key: !secret octoprint_api_key

camera:
  - platform: mjpeg
    name: OctoPrint
    still_image_url: !secret octoprint_cam_snap
    mjpeg_url: !secret octoprint_cam_stream

  - platform: generic
    name: octoprint_preview
    still_image_url: >
      {% if is_state('sensor.octoprint_filename_convert','unknown') %}
        https://hass.klompen.net/local/images/octoprint-placeholder.png
      {% else %}
        {{ states('sensor.octoprint_filename_convert') }}
      {% endif %}
    scan_interval: 5
    content_type: image/png

shell_command:
  octoprint_light_on: "curl -s http://192.168.178.80/api/printer/command -d '{\"command\":\"@WS_LIGHTSON\"}' -H 'Content-Type: application/json' -H 'X-Api-Key: {{ octo_api }}'"
  octoprint_light_off: "curl -s http://192.168.178.80/api/printer/command -d '{\"command\":\"@WS_LIGHTSOFF\"}' -H 'Content-Type: application/json' -H 'X-Api-Key: {{ octo_api }}'"

notify:
  - platform: rest
    name: "octoprint"
    resource: !secret octoprint_api_connection
    method: "POST_JSON"
    headers:
      X-Api-Key: !secret octoprint_api_key
    data:
      command: "connect"

sensor:
  - platform: mqtt
    state_topic: "octoPrint/progress/printing"
    value_template: "http://192.168.178.80/plugin/UltimakerFormatPackage/thumbnail/{{(value_json.path)|regex_replace(find='gcode', replace='png', ignorecase=True)}}"
    force_update: true
    name: 'octoprint_filename_convert'

  - platform: template
    sensors:
      octoprint_eta:
        friendly_name: 'Octoprint Print ETA'
        value_template: "{{ ((as_timestamp(now())| int) + (states(('sensor.octoprint_print_time_left')) | int)) | timestamp_local }}"