# https://github.com/cyberjunky/home-assistant-p2000
# https://github.com/leeuwte/home-assistant-p2000
sensor:
  - platform: p2000
    name: P2000 Someren
    gemeenten:
      - someren
    # capcodes:
    #   - 1234567

  # - platform: p2000
  #   name: P2000 Brabant Zuid Oost
  #   gemeenten:
  #     - brabant-zuidoost

  # - platform: p2000
  #   name: P2000 Limburg Noord
  #   gemeenten:
  #     - limburg-noord

  - platform: template
    sensors:
      p2000_someren_melding:
        friendly_name: "P2000 Someren Melding"
        value_template: "{{ state_attr('sensor.p2000_someren', 'melding') }}"
      # p2000_brabant_zuidoost_melding:
      #   friendly_name: "P2000 Brabant Zuid Oost Melding"
      #   value_template: "{{ state_attr('sensor.p2000_brabant_zuid_oost', 'melding') }}"
      # p2000_limburg_noord_melding:
      #   friendly_name: "P2000 Limburg Noord Melding"
      #   value_template: "{{ state_attr('sensor.p2000_limburg_noord', 'melding') }}"