# Pixel IT Smart Clock
sensor:
- platform: rest
  resource: http://192.168.178.251:5050/api/appdaemon/pixelit_sensor
  method: POST
  headers:
    Content-Type: "application/json"
  payload: '{}'
  name: Pixelit
  value_template: > 
      {{ value_json.state }}
  scan_interval: 300

notify:
  - name: pixelit
    platform: rest
    method: POST_JSON
    headers:
      Content-Type: "application/json"
    resource: http://192.168.178.251:5050/api/appdaemon/pixelit_add
    title_param_name: "title"

rest_command:
  pixelit_delete:
    url: http://192.168.178.251:5050/api/appdaemon/pixelit_delete
    method: POST
    payload: '{"title": "{{ title }}"}'
    content_type:  'application/json; charset=utf-8'

  pixelit_update:
    url: http://192.168.178.251:5050/api/appdaemon/pixelit_update
    method: POST
    payload: '{"title": "{{ title }}","message": "{{ message }}"}'
    content_type:  'application/json; charset=utf-8'

