sensor:
  - platform: snmp
    name: 'Printer Paginas'
    host: 192.168.178.240
    baseoid: 1.3.6.1.2.1.43.10.2.1.4.1.1
    accept_errors: true
    scan_interval: 3600

  - platform: snmp
    name: 'Printer Toner - Zwart'
    host: 192.168.178.240
    baseoid: 1.3.6.1.2.1.43.11.1.1.9.1.1
    accept_errors: true
    scan_interval: 86400
    unit_of_measurement: '%'

  - platform: snmp
    name: 'Printer Toner - Cyaan'
    host: 192.168.178.240
    baseoid: 1.3.6.1.2.1.43.11.1.1.9.1.2
    accept_errors: true
    scan_interval: 86400
    unit_of_measurement: '%'

  - platform: snmp
    name: 'Printer Toner - Magenta'
    host: 192.168.178.240
    baseoid: 1.3.6.1.2.1.43.11.1.1.9.1.3
    accept_errors: true
    scan_interval: 86400
    unit_of_measurement: '%'

  - platform: snmp
    name: 'Printer Toner - Geel'
    host: 192.168.178.240
    baseoid: 1.3.6.1.2.1.43.11.1.1.9.1.4
    accept_errors: true
    scan_interval: 86400
    unit_of_measurement: '%'