sensor:
  - platform: rdw
    name: "Seat Leon"
    plate: H240SV
    sensors:
      - expdate
      - insured
  - platform: rdw
    name: "Volkswagen Polo"
    plate: XT249K
    sensors:
      - expdate
      - insured