---
# Sensors are gathering information about states and conditions.
#
# This loads up my sensor configurations
#
# https://www.home-assistant.io/components/sensor/
#
sensor:
  # https://www.home-assistant.io/components/time_date/
  # The time and date (time_date) sensor platform simple 
  # displays the time in various formats, the date, or both.
  - platform: time_date
    display_options:
      - time
      - date
      - time_utc

  # The cert_expiry sensor fetches information from a configured URL
  # and displays the certificate expiry in days.
  - platform: cert_expiry
    host: !secret http_sensor_cert