---
# Sensors are gathering information about states and conditions.
#
# This loads up my sensor configurations
#
# https://www.home-assistant.io/components/sensor/
#
sensor:
  # Vaatwasser
  - platform: mqtt
    name: "Vaatwasser Energy"
    state_topic: "tele/vaatwasser/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Vaatwasser Power"
    state_topic: "tele/vaatwasser/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Vaatwasser Voltage"
    state_topic: "tele/vaatwasser/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
    unit_of_measurement: "V"
  - platform: mqtt
    name: "Vaatwasser Current"
    state_topic: "tele/vaatwasser/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Current"] }}'
    unit_of_measurement: "A"

  # Afzuigkap
  - platform: mqtt
    name: "Afzuigkap Energy"
    state_topic: "tele/afzuigkap/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Afzuigkap Power"
    state_topic: "tele/afzuigkap/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Afzuigkap Voltage"
    state_topic: "tele/afzuigkap/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
    unit_of_measurement: "V"
  - platform: mqtt
    name: "Afzuigkap Current"
    state_topic: "tele/afzuigkap/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Current"] }}'
    unit_of_measurement: "A"

  # Server
  - platform: mqtt
    name: "Server Energy"
    state_topic: "tele/server/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Server Power"
    state_topic: "tele/server/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Server Voltage"
    state_topic: "tele/server/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
    unit_of_measurement: "V"
  - platform: mqtt
    name: "Server Current"
    state_topic: "tele/server/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Current"] }}'
    unit_of_measurement: "A"


  # https://www.home-assistant.io/components/sensor.version/
  # The version sensor platform is displaying the
  # available version online.
  - platform: version
    name: version_available
    source: hassio
    image: qemux86-64

  # The version sensor platform is displaying the
  # current version.
  - platform: version
    name: version_current


  # https://www.home-assistant.io/components/time_date/
  # The time and date (time_date) sensor platform simple 
  # displays the time in various formats, the date, or both.
  - platform: time_date
    display_options:
      - time
      - date
      - time_utc


  # The cert_expiry sensor fetches information from a configured URL
  # and displays the certificate expiry in days.
  - platform: cert_expiry
    host: !secret http_sensor_cert