# input_slider:
#   auto_pump_minutes:
#     name: Minutes after sunset
#     icon: mdi:timer
#     initial: 30
#     min: 0
#     max: 1200
#     step: 10
#   auto_pump_duration:
#     name: Duration hours
#     icon: mdi:timer
#     initial: 4
#     min: 0
#     max: 8
#     step: 0.5

# sensor:
#   - platform: template
#     sensors:
#       auto_pump_start:
#         friendly_name: 'Pomp aan om'
#         value_template: '{{ (as_timestamp(states.sun.sun.attributes.next_setting) + (states("input_slider.auto_pump_minutes") | int)  * 60)  | timestamp_custom("%H:%M") }}'
#       auto_pump_stop:
#         friendly_name: 'Pomp uit om'
#         value_template: '{{ ( as_timestamp(states.sun.sun.attributes.next_setting) + (states("input_slider.auto_pump_minutes") | int)  * 60 + (states("input_slider.auto_pump_duration") | float) * 60 * 60  )  | timestamp_custom("%H:%M") }}'
#       auto_pump_minutes:
#         friendly_name: 'Pomp aan '
#         value_template: '{{ "%d minuten na zonsondergang" | format(states("input_slider.auto_pump_minutes") | int) }}'
#       auto_pump_duration:
#         friendly_name: 'Pomp aan voor'
#         value_template: '{{ "%0.1f uur" | format(states("input_slider.auto_pump_duration") | float) }}'

input_boolean:
  swimming_season:
    icon: mdi:swim
    name: Zwem seizoen

input_select:
  pool_pump:
    icon: mdi:engine
    initial: Auto
    name: Zwembadpomp
    options:
      - "Auto"
      - "Aan"
      - "Uit"

sensor:
  - platform: template
    sensors:
      pool_pump_status:
        value_template: '{% if is_state("switch.zwembadpomp", "on") %}Running{% else %}Stopped{% endif %}'
        friendly_name: 'Zwembadpomp status'

      pool_pump_time_on:
        value_template: '{{ states.sensor.pool_pump_running_today.attributes.value }}'
        friendly_name: 'Zwembadpomp uren'

  - platform: history_stats
    name: Pool Pump running today
    entity_id: sensor.pool_pump_status
    state: 'Running'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'