---
# https://github.com/custom-components/sensor.unifigateway
#
sensor:
  - platform: unifigateway
    host: !secret device_tracker_unifi_host
    port: 8443
    version: v5
    site_id: !secret device_tracker_unifi_siteid
    verify_ssl: false
    username: !secret device_tracker_unifi_user
    password: !secret device_tracker_unifi_pass
    monitored_conditions:
      - www
      - wan
      - vpn
      - lan
      - wlan
      - alerts
      - firmware


  - platform: template
    sensors:
      unifi_gateway_wan_download:
        friendly_name: 'WAN Download'
        icon_template: "mdi:progress-download"
        unit_of_measurement: KBps
        value_template: "{{ (states.sensor.unifi_gateway_www.attributes['rx_bytes-r'] / 100) | int }}"
      unifi_gateway_wan_cpu:
        friendly_name: "CPU"
        unit_of_measurement: "%"
        value_template: "{{ states.sensor.unifi_gateway_wan.attributes['gw_system-stats']['cpu'] }}"
      unifi_gateway_wan_mem:
        friendly_name: "Memory"
        unit_of_measurement: "%"
        value_template: "{{ states.sensor.unifi_gateway_wan.attributes['gw_system-stats']['mem'] }}"
      unifi_gateway_lan_num_user:
        friendly_name: 'Users LAN'
        value_template: '{{ states.sensor.unifi_gateway_lan.attributes.num_user }}'
      unifi_gateway_wlan_num_user:
        friendly_name: 'Users WLAN'
        value_template: '{{ states.sensor.unifi_gateway_wlan.attributes.num_user }}'
      unifi_gateway_wlan_num_guest:
        friendly_name: 'Guests WLAN'
        value_template: '{{ states.sensor.unifi_gateway_wlan.attributes.num_guest }}'

  # # Webshop scrape sensor G3 Instant camera
  # - platform: scrape
  #   name: "G3 instant title"
  #   resource: https://eu.store.ui.com/collections/unifi-protect/products/unifi-protect-g3-instant-camera
  #   select: ".comProduct__title--wrapper"
  #   scan_interval: 60