input_select:
  dishwasher_status:
    name: Vaatwasser Status
    options:
      - Idle
      - Running
      - Drying
      - Clean
      - Power OFF
    initial: Idle
  washing_machine_status:
    name: Wasmachine Status
    options:
      - Idle
      - Running
      - Finishing
      - Clean
      - Power OFF
    initial: Idle
  dryer_status:
    name: Droger Status
    options:
      - Idle
      - Running
      - Finishing
      - Dry
      - Power OFF
    initial: Idle
  afzuigkap_status:
    name: Afzuigkap Status
    options:
      - 'on'
      - 'off'
    initial: 'off'

sensor:
  - platform: template
    sensors:
      washing_machine_status:
        value_template: '{{ states.input_select.washing_machine_status.state}}'
        friendly_name: 'Wasmachine Status'
        unique_id: 74b7e122-ce98-4282-8518-b1e28ae33482
      dishwasher_status:
        value_template: '{{ states.input_select.dishwasher_status.state}}'
        friendly_name: 'Vaatwasser Status'
        unique_id: ac05d513-193d-48b2-a937-b379009aa0ba
      dryer_status:
        value_template: '{{ states.input_select.dryer_status.state}}'
        friendly_name: 'Droger Status'
        unique_id: 70891148-7efa-43d4-b3aa-3cb1fd7dfa43
      afzuigkap_status:
        value_template: '{{ states.input_select.afzuigkap_status.state}}'
        friendly_name: 'Afzuigkap Status'
        unique_id: e6ef9e03-58eb-4696-b969-fb9eb98db852