sensor:
  # https://www.home-assistant.io/components/waze_travel_time/
  # The waze_travel_time sensor provides travel time from the Waze.
  # JEROEN
  - platform: waze_travel_time
    name: Reistijd Jeroen
    origin: person.jeroen
    destination: zone.home
    region: EU

  - platform: waze_travel_time
    name: Reistijd Jeroen e-Quest SD26
    origin: person.jeroen
    destination: zone.e_quest_sd26
    region: EU

  - platform: waze_travel_time
    name: Reistijd Jeroen e-Quest SD33
    origin: person.jeroen
    destination: zone.e_quest_sd33
    region: EU

  - platform: waze_travel_time
    name: Reistijd Ouders Jeroen
    origin: person.jeroen
    destination: zone.ouders
    region: EU