---
#
# This handles the loading of my weather platforms.
#
# https://www.home-assistant.io/components/weather/
#
weather:

# DarkSky
# https://www.home-assistant.io/components/weather.darksky/
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily

# # Air Visual
# # https://www.home-assistant.io/integrations/airvisual/
# airvisual:
#   api_key: !secret airvisual_api
#   geographies:
#     latitude: !secret zone_home_latitude
#     longitude: !secret zone_home_longitude

sensor:
  # DarkSky
  # https://www.home-assistant.io/integrations/darksky/
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - summary
      - temperature
      - humidity
      - wind_speed
    language: nl

  # Buienrader
  # https://www.home-assistant.io/integrations/sensor.buienradar/
  - platform: buienradar
    monitored_conditions:
      - temperature
      - humidity
      - windspeed
      - precipitation
      - irradiance