---
binary_sensor:

  # This is the workday sensor. This binary sensor tells me if it is
  # a workday today. It takes into account holidays as well!
  #
  # This is pretty useful for a lot of automations.
  #
  # https://www.home-assistant.io/components/binary_sensor.workday/
  #
  - platform: workday
    country: NLD
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]
    # add_holidays:
    #   - '2021-04-27' #Koningsdag
    #   - '2020-01-01' #Nieuwjaarsdag
    #   - '2020-04-10' #Goede vrijdag
    #   - '2020-04-12' #Pasen
    #   - '2020-04-13' #Paasmaandag
    #   - '2020-04-27' #Koningsdag
    #   - '2020-05-05' #Bevrijdingsdag
    #   - '2020-05-21' #O.H. Hemelvaart
    #   - '2020-05-31' #Pinksteren
    #   - '2020-06-01' #Pinkstermaandag
    #   - '2020-12-25' #Kerstmis
    #   - '2020-12-26' #2de Kerstdag
    #   - '2021-01-01' #Nieuwjaarsdag
    #   - '2021-04-02' #Goede vrijdag
    #   - '2021-04-04' #Pasen
    #   - '2021-04-05' #Paasmaandag