homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret zone_home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Timezone
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml
  # Contains the URL that Home Assistant is available on the internet.
  internal_url: !secret ha_internal_url
  external_url: !secret ha_external_url
  # List of folders that can be used as sources for sending files.
  allowlist_external_dirs:
    - /config

  # Load packages
  packages: !include_dir_named integrations/

# Discover some devices automatically
#discovery:

# Load scripts
script: !include scripts.yaml

# Load Scenes
# https://www.home-assistant.io/docs/scene/editor/
scene: !include scenes.yaml

# Lovelace Mode
lovelace:
  mode: yaml
  # Include external resource
  resources: !include dwains-dashboard/resources/custom_resources.yaml