homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret zone_home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Currency
  currency: EUR
  # Country
  country: NL
  # Timezone
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml
  # Contains the URL that Home Assistant is available on the internet.
  internal_url: !secret ha_internal_url
  external_url: !secret ha_external_url
  # Multi-factor authentication
  auth_mfa_modules:
    - type: totp
  # List of folders that can be used as sources for sending files.
  allowlist_external_dirs:
    - /config

  # Load packages
  packages: !include_dir_named integrations/

# Discover some devices automatically
#discovery:

# Load scripts
script: !include scripts.yaml

# Load Scenes
# https://www.home-assistant.io/docs/scene/editor/
scene: !include scenes.yaml

frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

  themes: !include_dir_merge_named themes/
# Lovelace Mode
lovelace:
  mode: yaml
  # Include external resource
  resources: !include custom_resources.yaml
  dashboards:
    lovelace-klompen:
      mode: yaml
      title: Klompen
      show_in_sidebar: true
      filename: ui-klompen.yaml
