homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret zone_home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml

  # Load packages
  packages: !include_dir_named integrations

# Discover some devices automatically
#discovery:


# Frontend and HTTP
frontend:
  themes: !include_dir_named themes
  javascript_version: auto

# Lovelace Mode
lovelace:
  mode: yaml

# Panel
panel_iframe:
  deconz:
    title: 'deCONZ'
    #url: 'http://192.168.178.251:40850/pwa'
    url: 'https://hass.klompen.biz/local/deconz.html'
    icon: 'mdi:graphql'

script: !include scripts.yaml

# Browser Mod
# https://github.com/thomasloven/hass-browser_mod
# browser_mod:
#   95f0a1b5-438c0d1f:
#     name: pc-jeroen
#   768fc0ad-b97ed01b:
#     name: gsm-jeroen