homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret zone_home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Timezone
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml

  # Load packages
  packages: !include_dir_named integrations/

# Discover some devices automatically
#discovery:

# Customizer Component
# https://github.com/andrey-git/home-assistant-customizer
# customizer:
#   custom_ui: local

script: !include scripts.yaml

# Load Scenes
# https://www.home-assistant.io/docs/scene/editor/
scene: !include scenes.yaml

# Lovelace Mode
lovelace:
  mode: yaml

# Frontend and HTTP
frontend:
  themes: !include_dir_merge_named themes
#  themes: !include_dir_named themes
  extra_html_url:
    - /local/dwains-theme/fonts/fontawesome/hass-fontawesome-solid.html
    - /local/dwains-theme/fonts/fontawesome/hass-fontawesome-regular.html
    - /local/dwains-theme/fonts/fontawesome/hass-fontawesome-light.html

# Load Browser Mod
# https://github.com/thomasloven/hass-browser_mod
browser_mod:

#Dwains theme definitions (this is for doing all the jinja2 inside YAML files)
dwains_theme:
  information:
    version: '1.1.4'
  translations:
    !include_dir_merge_named dwains-theme/translations/
  configuration:
    !include_dir_merge_named dwains-theme/configs/
  icons:
    !include dwains-theme/configs/icons.yaml

#Sensor for latest version
sensor:
  - platform: scrape
    resource: https://dwains-theme.dwainscheeren.nl/version?v=1.1.4
    name: Dwains Theme Version
    select: ".current-version h1"
    value_template: '{{ value.split(":")[1] }}'

#Input select
input_select:
  #Theme selector
  theme_selector:
    name: Theme Selector
    options:
      - Auto Mode
      - Dark Mode
      - Light Mode