title: Automations
path: automations
cards:
  - type: vertical-stack
    cards:
      - type: custom:decluttering-card
        template: quick-access-menu
        variables:
          - name1: Verlichting
          - icon1: mdi:floor-lamp
          - path1: lights
      - type: custom:decluttering-card
        template: header
        variables:
          - content: '## Automations'
      - type: custom:decluttering-card
        template: header
        variables:
          - content: '##### Zet aan / uit'
      - type: horizontal-stack
        cards:
          - !include ../includes/blank-card.yaml
          - type: custom:decluttering-card
            template: button
            variables:
              - entity: group.deur_notifications
              - name: Deur
              - icon: mdi:door
              - label: Notificaties
              - show_state: true
              - grid:
                  - grid-template-areas: '"i" "n" "l" "s"'
                  - grid-template-columns: 1fr
                  - grid-template-rows: 1fr min-content min-content
              - tap_action:
                  action: toggle
                  haptic: light
          - type: custom:decluttering-card
            template: button
            variables:
              - entity: group.beweging_notifications
              - name: Beweging
              - icon: mdi:motion-sensor
              - label: Notificaties
              - show_state: true
              - grid:
                  - grid-template-areas: '"i" "n" "l" "s"'
                  - grid-template-columns: 1fr
                  - grid-template-rows: 1fr min-content min-content
              - tap_action:
                  action: toggle
                  haptic: light
          - type: custom:decluttering-card
            template: button
            variables:
              - entity: group.all_automations
              - name: Automations
              - icon: mdi:alpha-a-box
              - label: Alle automations
              - show_state: true
              - grid:
                  - grid-template-areas: '"i" "n" "l" "s"'
                  - grid-template-columns: 1fr
                  - grid-template-rows: 1fr min-content min-content
              - tap_action:
                  action: toggle
                  haptic: light
          - !include ../includes/blank-card.yaml
      - type: horizontal-stack
        cards:
          - !include ../includes/blank-card.yaml
          - type: custom:button-card
            color_type: blank-card
            aspect_ratio: 1/1
          - type: custom:button-card
            color_type: blank-card
            aspect_ratio: 1/1
          - type: custom:decluttering-card
            template: button
            variables:
              - entity: group.vakantie_modus
              - name: Vakantie
              - icon: mdi:beach
              - label: Modus
              - show_state: true
              - grid:
                  - grid-template-areas: '"i" "n" "l" "s"'
                  - grid-template-columns: 1fr
                  - grid-template-rows: 1fr min-content min-content
              - tap_action:
                  action: toggle
                  haptic: light
          - !include ../includes/blank-card.yaml
      - !include ../includes/bottom-card.yaml