title: Beveiliging
path: security
icon: 'mdi:cctv'
cards:
  - type: vertical-stack
    cards:
      - type: custom:decluttering-card
        template: quick-access-menu
        variables:
          - name1: Alarm
          - icon1: mdi:shield-home
          - path1: alarm
      - type: custom:decluttering-card
        template: header
        variables:
          - content: '## Beveiliging'
      - type: custom:decluttering-card
        template: header
        variables:
          - content: "##### Camera's"
      - type: horizontal-stack
        cards:
          - !include ../includes/blank-card.yaml
          - type: picture-entity
            style: |
              ha-card {
                border-radius: {{ states('input_select.border_radius') }};
                box-shadow: {{ states('input_select.box_shadow') }};
                overflow: hidden;
              }
            entity: camera.voordeur
            #camera_view: "live"
            show_state: false
            title: Camera's
            aspect_ratio: 16x9
            #deep_press: true
          - !include ../includes/blank-card.yaml
      - type: horizontal-stack
        cards:
          - !include ../includes/blank-card.yaml
          - type: picture-entity
            style: |
              ha-card {
                border-radius: {{ states('input_select.border_radius') }};
                box-shadow: {{ states('input_select.box_shadow') }};
                overflow: hidden;
              }
            entity: camera.carport
            #camera_view: "live"
            show_state: false
            title: Camera's
            aspect_ratio: 16x9
            #deep_press: true
          - !include ../includes/blank-card.yaml
      - type: horizontal-stack
        cards:
          - !include ../includes/blank-card.yaml
          - type: picture-entity
            style: |
              ha-card {
                border-radius: {{ states('input_select.border_radius') }};
                box-shadow: {{ states('input_select.box_shadow') }};
                overflow: hidden;
              }
            entity: camera.tuin
            #camera_view: "live"
            show_state: false
            title: Camera's
            aspect_ratio: 16x9
            #deep_press: true
          - !include ../includes/blank-card.yaml

  - type: vertical-stack
    cards:
      - type: custom:decluttering-card
        template: header
        variables:
          - content: '##### Deuren'
      - type: horizontal-stack
        cards:
          - !include ../includes/blank-card.yaml
          - type: custom:decluttering-card
            template: button
            variables:
              - entity: binary_sensor.contact_garagedeur
              - name: Garagedeur
              - icon: "[[[ if (entity.state === 'on') return 'mdi:door-open'; else return 'mdi:door'; ]]]"
              - show_last_changed: true
              - tap_action:
                  action: more-info
                  haptic: light
              - hold_action:
                  action: more-info
                  haptic: heavy
          - type: custom:decluttering-card
            template: button
            variables:
              - entity: binary_sensor.contact_achterdeur
              - name: Achterdeur
              - icon: "[[[ if (entity.state === 'on') return 'mdi:door-open'; else return 'mdi:door'; ]]]"
              - show_last_changed: true
              - tap_action:
                  action: more-info
                  haptic: light
              - hold_action:
                  action: more-info
                  haptic: heavy
          - type: custom:button-card
            color_type: blank-card
            aspect_ratio: 1/1
          - !include ../includes/blank-card.yaml
      - type: custom:decluttering-card
        template: header
        variables:
          - content: '##### Ramen'
      - type: horizontal-stack
        cards:
          - !include ../includes/blank-card.yaml
          - type: custom:decluttering-card
            template: button
            variables:
              - entity: binary_sensor.contact_slaapkamerraam
              - name: Slaapkamer
              - icon: "[[[ if (entity.state === 'on') return 'mdi:window-closed'; else return 'mdi:window-open'; ]]]"
              - show_last_changed: true
              - tap_action:
                  action: more-info
                  haptic: light
              - hold_action:
                  action: more-info
                  haptic: heavy
          - type: custom:decluttering-card
            template: button
            variables:
              - entity: binary_sensor.contact_kleine_kamerraam
              - name: Kleine kamer
              - icon: "[[[ if (entity.state === 'on') return 'mdi:window-closed'; else return 'mdi:window-open'; ]]]"
              - show_last_changed: true
              - tap_action:
                  action: more-info
                  haptic: light
              - hold_action:
                  action: more-info
                  haptic: heavy
          - type: custom:decluttering-card
            template: button
            variables:
              - entity: binary_sensor.contact_logeerkamerraam
              - name: Logeerkamer
              - icon: "[[[ if (entity.state === 'on') return 'mdi:window-closed'; else return 'mdi:window-open'; ]]]"
              - show_last_changed: true
              - tap_action:
                  action: more-info
                  haptic: light
              - hold_action:
                  action: more-info
                  haptic: heavy
          - !include ../includes/blank-card.yaml
      - type: horizontal-stack
        cards:
          - !include ../includes/blank-card.yaml
          - type: custom:decluttering-card
            template: button
            variables:
              - entity: binary_sensor.contact_zolderraam
              - name: Zolder
              - icon: "[[[ if (entity.state === 'on') return 'mdi:window-closed'; else return 'mdi:window-open'; ]]]"
              - show_last_changed: true
              - tap_action:
                  action: more-info
                  haptic: light
              - hold_action:
                  action: more-info
                  haptic: heavy
          - type: custom:button-card
            color_type: blank-card
            aspect_ratio: 1/1
          - type: custom:button-card
            color_type: blank-card
            aspect_ratio: 1/1
          - !include ../includes/blank-card.yaml
      - type: custom:decluttering-card
        template: header
        variables:
          - content: '##### Beweging'
      - type: horizontal-stack
        cards:
          - !include ../includes/blank-card.yaml
          - type: custom:decluttering-card
            template: button
            variables:
              - entity: binary_sensor.motion_woonkamer
              - name: Woonkamer
              - icon: "[[[ if (entity.state === 'on') return 'mdi:motion-sensor'; else return 'mdi:walk'; ]]]"
              - show_last_changed: true
              - tap_action:
                  action: more-info
                  haptic: light
              - hold_action:
                  action: more-info
                  haptic: heavy
          - type: custom:decluttering-card
            template: button
            variables:
              - entity: binary_sensor.motion_garage
              - name: Garage
              - icon: "[[[ if (entity.state === 'on') return 'mdi:motion-sensor'; else return 'mdi:walk'; ]]]"
              - show_last_changed: true
              - tap_action:
                  action: more-info
                  haptic: light
              - hold_action:
                  action: more-info
                  haptic: heavy
          - type: custom:decluttering-card
            template: button
            variables:
              - entity: binary_sensor.motion_slaapkamer
              - name: Slaapkamer
              - icon: "[[[ if (entity.state === 'on') return 'mdi:motion-sensor'; else return 'mdi:walk'; ]]]"
              - show_last_changed: true
              - tap_action:
                  action: more-info
                  haptic: light
              - hold_action:
                  action: more-info
                  haptic: heavy
          #- type: custom:button-card
          #  color_type: blank-card
          #  aspect_ratio: 1/1
          - !include ../includes/blank-card.yaml
      - type: custom:decluttering-card
        template: header
        variables:
          - content: '##### Alarmen'
      - type: horizontal-stack
        cards:
          - !include ../includes/blank-card.yaml
          - type: custom:decluttering-card
            template: button
            variables:
              - entity: binary_sensor.fib_fgsd002_overloop_brandmelder
              - name: Rookmelder overloop
              - icon: mdi:smoke-detector
              - show_last_changed: true
              - tap_action:
                  action: more-info
                  haptic: light
              - hold_action:
                  action: more-info
                  haptic: heavy
          - type: 'custom:button-card'
            color_type: blank-card
            aspect_ratio: 1/1
          - type: 'custom:button-card'
            color_type: blank-card
            aspect_ratio: 1/1
          - !include ../includes/blank-card.yaml

      - !include ../includes/bottom-card.yaml