house_information:
  favorites:
    - entity: binary_sensor.deurbel_knop
      icon_on: fas:bell
      icon_off: fas:bell
    - entity: binary_sensor.contact_garagedeur
      icon_on: fas:door-open
      icon_off: fas:door-closed
    - entity: binary_sensor.contact_achterdeur
      icon_on: fas:door-open
      icon_off: fas:door-closed
    - entity: input_select.washing_machine_status
    - entity: input_select.dryer_status
    - entity: input_select.dishwasher_status
  calendar:
    # - calendar.trash
    # - calendar.birthdays
    - calendar.jeroen
    - calendar.joyce
    - calendar.gezamenlijk