house_information:
  favorites:
    - entity: binary_sensor.deurbel_knop
      icon_on: fal:bell-on
      icon_off: fal:bell
    - entity: binary_sensor.contact_garagedeur
      icon_on: fal:door-open
      icon_off: fal:door-closed
    - entity: binary_sensor.contact_achterdeur
      icon_on: fal:door-open
      icon_off: fal:door-closed
  addons:
    - name: Kalender
      icon: fal:calendar-alt
      path: 'dwains-theme/addons/house_information/calendar/page.yaml'
      data:
        calendars:
          - calendar.jeroen
          - calendar.joyce
          - calendar.gezamenlijk