house_information:
  favorites:
    # - entity: binary_sensor.doorbell_button
    #   icon_on: fas:bell
    #   icon_off: fas:bell
    - entity: binary_sensor.contact_garagedeur
      icon_on: fas:door-open
      icon_off: fas:door-closed

  calendar:
    # - calendar.trash
    # - calendar.birthdays
    - calendar.jeroen
    - calendar.joyce
    - calendar.gezamenlijk