icons:
#   #Menu icons
#   menu_back: 'fas:question'
#   menu_home: 'fas:question'
#   menu_lights: 'fas:question'
#   menu_scenes: 'fas:question'
#   menu_cameras: 'fas:question'
#   menu_more_page: 'fas:question'

#   #Global icons
#   light_on: 'fas:question'
#   light_off: 'fal:smile-wink'

#   climate: 'fas:question'
#   climate_heating: 'fas:question'
#   climate_auto: 'fas:question'
#   climate_off: 'fas:question'
#   climate_heat: 'fas:question'

#   window_open: 'fas:question'
#   window_closed: 'fas:question'

#   door_open: 'fas:question'
#   door_closed: 'fas:question'

#   motion_on: 'fas:question'
#   motion_off: 'fas:question'

#   cover: 'fas:question'

#   device: 'fas:question'

#   media_player: 'fas:question'
  
#   vacuum: 'fas:question'

#   plant: 'fas:question'

#   alarm_disarmed: 'fas:question'
#   alarm_pending: 'fas:question'
#   alarm_armed_away: 'fas:question'
#   armed_home: 'fas:question'

#   #More page icons
  more_page_house_information: 'fal:home'
  more_page_house_data: 'fal:clinic-medical'
  more_page_settings: 'fal:cogs'
#   more_page_list_chevron: 'fas:question'

#   lock_locked: 'fas:question'
#   lock_unlocked: 'fas:question'