#more_addons:
  # - name: Statistics
  #   icon: far:chart-area
  #   path: 'user-package-sample/views/addons/statistics.yaml'
more_page:
    addons:
    #  addons:
      - name: Statistieken
        icon: fal:chart-area
        path: 'dwains-theme/addons/more_page/statistics/page.yaml'
      - name: Energie
        icon: fal:plug
        path: 'dwains-theme/addons/more_page/energy/page.yaml'
      - name: Afvalwijzer
        icon: fal:recycle
        path: 'dwains-theme/addons/more_page/afvalwijzer/page.yaml'
      - name: P2000
        icon: fal:ambulance
        path: 'dwains-theme/addons/more_page/p2000/page.yaml'
      - name: Ambilight + Hue
        icon: fal:tv
        path: 'dwains-theme/addons/more_page/ambilight/page.yaml'
      - name: AdGuard
        icon: fal:ad
        path: 'dwains-theme/addons/more_page/adguard/page.yaml'
      - name: ISP
        icon: fal:tachometer-alt
        path: 'dwains-theme/addons/more_page/isp/page.yaml'
      - name: Zwave
        icon: fal:wifi
        path: 'dwains-theme/addons/more_page/zwave/page.yaml'