more_page:
    addons:
      - name: Statistieken
        icon: fal:chart-area
        path: 'dwains-theme/addons/more_page/statistics/page.yaml'
      - name: Energie
        icon: fal:plug
        path: 'dwains-theme/addons/more_page/energy/page.yaml'
      - name: Afvalwijzer
        icon: fal:recycle
        path: 'dwains-theme/addons/more_page/afvalwijzer/page.yaml'
        data:
          wastecollector: blink
          # sort_attribute: Sort-date
          # language: nl
      - name: P2000
        icon: fal:ambulance
        path: 'dwains-theme/addons/more_page/p2000/page.yaml'
      - name: Ambilight + Hue
        icon: fal:tv
        path: 'dwains-theme/addons/more_page/ambilight/page.yaml'
      - name: AdGuard
        icon: fal:ad
        path: 'dwains-theme/addons/more_page/adguard/page.yaml'
      - name: Brandstofprijzen
        icon: fal:gas-pump
        path: 'dwains-theme/addons/more_page/fuel_prices/page.yaml'
      - name: ISP
        icon: fal:tachometer-alt
        path: 'dwains-theme/addons/more_page/unifi/page.yaml'
      - name: Zwave
        icon: fal:wifi
        path: 'dwains-theme/addons/more_page/zwave/page.yaml'
      - name: Coronavirus
        icon: fal:disease
        path: 'dwains-theme/addons/more_page/coronavirus/page.yaml'
      - name: Nextcloud
        icon: fal:cloud
        path: 'dwains-theme/addons/more_page/nextcloud/page.yaml'
      - name: TEST 2
        icon: fal:chart-area
        path: 'dwains-theme/addons/more_page/test2/page.yaml'
      - name: DeepStack
        icon: fal:brain
        path: 'dwains-theme/addons/more_page/deepstack/page.yaml'
      - name: TEST 3
        icon: fal:chart-area
        path: 'dwains-theme/addons/more_page/test3/page.yaml'