#more_addons:
  # - name: Statistics
  #   icon: far:chart-area
  #   path: 'user-package-sample/views/addons/statistics.yaml'
more_page:
    addons:
    #  addons:
      - name: Statistieken
        icon: fal:chart-area
        path: 'dwains-theme/addons/more_page/statistics/page.yaml'
      - name: Energie
        icon: fal:plug
        path: 'dwains-theme/addons/more_page/energy/page.yaml'
      - name: Afvalwijzer
        icon: fal:recycle
        path: 'dwains-theme/addons/more_page/afvalwijzer/page.yaml'
        data:
          afval_vandaag: sensor.blink_vandaag
          afval_morgen: sensor.blink_morgen
          afval_rest: sensor.blink_restafval
          afval_gft: sensor.blink_gft
          afval_pmd: sensor.blink_pmd
          afval_papier: sensor.blink_papier
      - name: P2000
        icon: fal:ambulance
        path: 'dwains-theme/addons/more_page/p2000/page.yaml'
      - name: Ambilight + Hue
        icon: fal:tv
        path: 'dwains-theme/addons/more_page/ambilight/page.yaml'
      - name: AdGuard
        icon: fal:ad
        path: 'dwains-theme/addons/more_page/adguard/page.yaml'
      - name: ISP
        icon: fal:tachometer-alt
        path: 'dwains-theme/addons/more_page/unifi/page.yaml'
      - name: Zwave
        icon: fal:wifi
        path: 'dwains-theme/addons/more_page/zwave/page.yaml'
      - name: Coronavirus
        icon: fal:disease
        path: 'dwains-theme/addons/more_page/coronavirus/page.yaml'
      - name: TEST 2
        icon: fal:chart-area
        path: 'dwains-theme/addons/more_page/test2/page.yaml'