persons:
  - name: Joyce
    track: person.joyce
    picture_path: 'images/persons/joyce.png'
    # addons:
    #   - name: Map
    #     path: 'dwains-theme/addons/persons/map-joyce/page.yaml'
    page_entities:
      columns: 4
      entities:
        - entity: sensor.joyce_battery_level
        - entity: sensor.joyce_battery_state
        - entity: sensor.joyce_distance
        - entity: sensor.joyce_steps
  - name: Jeroen
    track: person.jeroen
    picture_path: 'images/persons/jeroen.png'
    # addons:
    #   - name: Map
    #     path: 'dwains-theme/addons/persons/map-jeroen/page.yaml'
    page_entities:
      columns: 4
      entities:
        - entity: sensor.iklumpke_battery_level
        - entity: sensor.iklumpke_battery_state
        - entity: sensor.iklumpke_distance
        - entity: sensor.iklumpke_steps
    more_entities:
      columns: 1
      entities:
        - entity: sensor.iklumpke_battery_level
        - entity: sensor.iklumpke_battery_state
        - entity: sensor.iklumpke_distance
        - entity: sensor.iklumpke_steps