rooms:
  - name: Woonkamer
    icon: fal:couch
    light: group.woonkamer_lights
    temperature: sensor.temp_woonkamer
    humidity: sensor.temp_woonkamer_humidity
    pressure: sensor.temp_woonkamer_pressure
    motion: binary_sensor.motion_woonkamer
    media_player: group.woonkamer_mediaplayers
    addons:
      - name: Sonos
        icon: fal:speaker
        path: 'dwains-theme/addons/rooms/woonkamer/sonos/page.yaml'
        button_path: 'dwains-theme/addons/rooms/woonkamer/sonos/button.yaml'
        data:
          entity: media_player.woonkamer
      - name: Drakenbloed
        icon: fal:leaf
        # icon: fal:spa
        path: 'dwains-theme/addons/rooms/woonkamer/plant/page.yaml'
        button_path: 'dwains-theme/addons/rooms/woonkamer/plant/button.yaml'
        data:
          plant: plant.drakenbloed
          plant_species: dracaena marginata

  - name: Eetkamer
    icon: fal:utensils
    light: group.eetkamer_lights
    climate: climate.woonkamer
    temperature: sensor.woonkamer_temperature
    humidity: sensor.woonkamer_humidity
    # vacuum:
    #   advanced_view: 'true'
    #   entity: vacuum.xiaomi_vacuum_cleaner
    #   camera: camera.rockrobo_map
    # plant: plant.olijfboom_links
    addons:
      - name: Stofzuiger
        icon: fal:vacuum-robot
        path: 'dwains-theme/addons/rooms/eetkamer/vacuum/page.yaml'
        button_path: 'dwains-theme/addons/rooms/eetkamer/vacuum/button.yaml'
        data:
          vacuum: vacuum.rockrobo
          # vacuum: vacuum.xiaomi_vacuum_cleaner
          map: camera.rockrobo_map
          rooms:
            - room: Woonkamer
              icon: fal:couch
            - room: Keuken
              icon: fal:refrigerator
            - room: Eetkamer
              icon: fal:coffee
            - room: Hal
              icon: fal:key-skeleton
            - room: Garage
              icon: fal:warehouse
          sensors:
            - name: Hoofdborstel
              sensor: sensor.vacuum_main_brush_left
              icon: mdi:broom
            - name: Zijborstel
              sensor: sensor.vacuum_side_brush_left
              icon: mdi:broom
            - name: Filter
              sensor: sensor.vacuum_filter_left
              icon: mdi:broom
            - name: Sensoren
              sensor: sensor.vacuum_sensor_dirty_left
              icon: mdi:air-filter
      - name: Sonos
        icon: fal:speaker
        path: 'dwains-theme/addons/rooms/eetkamer/sonos/page.yaml'
        button_path: 'dwains-theme/addons/rooms/eetkamer/sonos/button.yaml'
        data:
          entity: media_player.eetkamer

  - name: Keuken
    icon: fal:refrigerator
    light: group.keuken_lights
    media_player: media_player.hub_keuken
    device: group.keuken_devices
    addons:
      - name: Vaatwasser
        icon: fal:dryer
        path: 'dwains-theme/addons/rooms/keuken/dishwasher/page.yaml'
        button_path: 'dwains-theme/addons/rooms/keuken/dishwasher/button.yaml'
        data:
          entity: input_select.dishwasher_status
        #  navigation_path: /lovelace/keuken_addon_vaatwasser

  - name: Slaapkamer
    icon: fal:bed-alt
    light: group.slaapkamer_lights
    temperature: sensor.temp_slaapkamer
    humidity: sensor.temp_slaapkamer_humidity
    pressure: sensor.temp_slaapkamer_pressure
    motion: binary_sensor.motion_slaapkamer
    window: binary_sensor.contact_slaapkamerraam
    cover: cover.slaapkamer
    media_player: media_player.tv_slaapkamer

  - name: Kleine kamer
    icon: fal:briefcase
    light: light.kleine_kamer
    temperature: sensor.temp_kleine_kamer
    humidity: sensor.temp_kleine_kamer_humidity
    pressure: sensor.temp_kleine_kamer_pressure
    window: binary_sensor.contact_kleine_kamerraam
    addons:
      - name: Printer
        icon: fal:print
        path: 'dwains-theme/addons/rooms/kleine_kamer/printer/page.yaml'
        button_path: 'dwains-theme/addons/rooms/kleine_kamer/printer/button.yaml'
        data:
          entity: sensor.hp_m281fdw_status
      - name: Sonos
        icon: fal:speaker
        path: 'dwains-theme/addons/rooms/kleine_kamer/sonos/page.yaml'
        button_path: 'dwains-theme/addons/rooms/kleine_kamer/sonos/button.yaml'
        data:
          entity: media_player.boven

  - name: Logeerkamer
    icon: fal:bed
    light: light.logeerkamer
    temperature: sensor.temp_logeerkamer
    humidity: sensor.temp_logeerkamer_humidity
    pressure: sensor.temp_logeerkamer_pressure
    window: binary_sensor.contact_logeerkamerraam

  - name: Badkamer
    icon: fal:bath
    temperature: sensor.temp_badkamer
    humidity: sensor.temp_badkamer_humidity
    pressure: sensor.temp_badkamer_pressure

  - name: Garage
    icon: fal:warehouse
    light: group.garage_lights
    temperature: sensor.temp_garage
    humidity: sensor.temp_garage_humidity
    pressure: sensor.temp_garage_pressure
    motion: binary_sensor.motion_garage
    door: binary_sensor.contact_garagedeur
    #media_player: media_player.eetkamer
    addons:
      - name: Camera
        path: 'dwains-theme/addons/rooms/tuin/camera/page.yaml'
        button_path: 'dwains-theme/addons/rooms/tuin/camera/button.yaml'
        data:
          entity: camera.carport

  - name: Hal
    icon: fal:key-skeleton
    light: group.other_lights
    device: switch.deurbel_bel_actief
    addons:
      - name: Camera
        path: 'dwains-theme/addons/rooms/tuin/camera/page.yaml'
        button_path: 'dwains-theme/addons/rooms/tuin/camera/button.yaml'
        data:
          entity: camera.voordeur
    # page_entities:
    #   columns: 1
    #   show_title: 'true'
    #   entities:
    #     - entity: switch.deurbel_bel_actief

  - name: Tuin
    icon: fal:tree-alt
    light: group.buiten_lights
    temperature: sensor.temp_tuin
    humidity: sensor.temp_tuin_humidity
    pressure: sensor.temp_tuin_pressure
    door: binary_sensor.contact_achterdeur
    # plant: plant.olijfboom_rechts
    addons:
      - name: Sonos
        icon: fal:speaker
        path: 'dwains-theme/addons/rooms/tuin/sonos/page.yaml'
        button_path: 'dwains-theme/addons/rooms/tuin/sonos/button.yaml'
        data:
          entity: media_player.tuin
      - name: Olijfboom
        icon: fal:leaf
        # icon: fal:spa
        path: 'dwains-theme/addons/rooms/tuin/plant/page.yaml'
        button_path: 'dwains-theme/addons/rooms/tuin/plant/button.yaml'
        data:
          plant: plant.olijfboom
          plant_species: olea europaea
          # plant2: plant.olijfboom_links
          # plant2_species: olea europaea
      - name: Camera
        path: 'dwains-theme/addons/rooms/tuin/camera/page.yaml'
        button_path: 'dwains-theme/addons/rooms/tuin/camera/button.yaml'
        data:
          entity: camera.tuin

  - name: Zolder
    icon: fal:box-full
    temperature: sensor.temp_zolder
    humidity: sensor.temp_zolder_humidity
    pressure: sensor.temp_zolder_pressure
    window: binary_sensor.contact_zolderraam
    #device: group.zolder_devices
    addons:
      - name: Sonos
        icon: fal:speaker
        path: 'dwains-theme/addons/rooms/zolder/sonos/page.yaml'
        button_path: 'dwains-theme/addons/rooms/zolder/sonos/button.yaml'
        data:
          entity: media_player.zolder
      - name: Wasmachine
        icon: fal:washer
        path: 'dwains-theme/addons/rooms/zolder/washingmachine/page.yaml'
        button_path: 'dwains-theme/addons/rooms/zolder/washingmachine/button.yaml'
        data:
          entity: input_select.washing_machine_status
      - name: Droger
        icon: fal:dryer-alt
        path: 'dwains-theme/addons/rooms/zolder/dryer/page.yaml'
        button_path: 'dwains-theme/addons/rooms/zolder/dryer/button.yaml'
        data:
          entity: input_select.dryer_status
    # page_entities:
    #   columns: 1 #optional
    #   show_title: 'false' #optional
    #   entities:
    #     - entity: sensor.reistijd_jeroen_alfion
    #     - entity: sensor.reistijd_joycejeroen