  # button 2002 On
  # button 2001 Move up (with on/off)
  # button 2003 Stop_

  # button 1002 Off
  # button 1001 Move down (with on/off)
  # button 1003 Stop_ (with on/off)

  # button 3002 Recall scene 1
  # button 4002 Recall scene 2

- alias: "AB kleine kamer: AAN"
  initial_state: on
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_kleine_kamer
      event: 2002
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.kleine_kamer
        brightness_pct: 100

- alias: "AB kleine kamer: UIT"
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_kleine_kamer
      event: 1002
  action:
    - service: light.turn_off
      entity_id:
          - light.kleine_kamer


- alias: 'AB kleine kamer: Increase brightness'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_kleine_kamer
      event: 2001
  action:
    - service: deconz.configure
      data:
        entity: light.kleine_kamer
        field: "/state"
        data: {"bri_inc":254, "transitiontime":50}

- alias: 'AB kleine kamer: Decrease brightness'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_kleine_kamer
      event: 1001
  action:
    - service: deconz.configure
      data:
        entity: light.kleine_kamer
        field: "/state"
        data: {"bri_inc":-254, "transitiontime":50}

- alias: 'AB kleine kamer: Stop brightness'
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: ab_kleine_kamer
        event: 1003
    - platform: event
      event_type: deconz_event
      event_data:
        id: ab_kleine_kamer
        event: 2003
  action:
    - service: deconz.configure
      data:
        entity: light.kleine_kamer
        field: "/state"
        data: {"bri_inc":0}