# When we detect power being drawn from the dishwasher,
# mark the dishwasher as using power
 
- alias: Set dishwasher active when power detected
  initial_state: 'true'
  trigger:
    - platform: numeric_state
      entity_id: sensor.vaatwasser_power
      above: 10
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Idle
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Clean
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Drying
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: Running


# When the power level drops below 10, and the Dishwasher is set to
# the 'Running' state, mark the Dishwasher to Drying
 
- alias: Set dishwasher drying when power drops
  initial_state: 'true'
  trigger:
    - platform: numeric_state
      entity_id: sensor.vaatwasser_power
      below: 10
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Running
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: Drying


# Once the dishwasher status has been 'Drying' for 30 minutes, mark the
# dishwasher as clean
 
- alias: Set dishwasher clean
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: input_select.dishwasher_status
      to: Drying
      for:
        minutes: 15
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Drying
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: Clean


# When the power drops and the dishwasher is Clean or Drying, someone has
# turned the Dishwasher off and emptied it. We should do this when the state
# of the Dishwasher is clean or Finishing, just incase someone opens the
# Dishwasher before the 30 minute timeout has been reached.
 
- alias: Set Dishwasher dirty when power off
  initial_state: 'true'
  trigger:
    - platform: numeric_state
      entity_id: sensor.vaatwasser_power
      below: 0.8
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.vaatwasser_power
        below: 0.8
      - condition: or
        conditions:
        - condition: state
          entity_id: input_select.dishwasher_status
          state: Clean
        - condition: state
          entity_id: input_select.dishwasher_status
          state: Drying
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: Idle


- alias: Set vaatwasser to idle when powered ON
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: switch.vaatwasser
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Power OFF
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: Idle


- alias: Set vaatwasser to POWER OFF when power is OFF
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: switch.vaatwasser
      to: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: Power OFF


# Vaatwasser Gereed Notificatie
- alias: Send alert when dishwasher is clean
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: input_select.dishwasher_status
      to: Clean
#    - platform: state
#      entity_id: person.jeroen
#      to: 'home'
#      for:
#        minutes: 3
#    - platform: state
#      entity_id: person.joyce
#      to: 'home'
#      for:
#        minutes: 3
  condition:
    condition: and
    conditions:
      - condition: time
        before: '01:30:00'
        after: '08:00:00'
#      - condition: state
#        entity_id: group.device_status
#        state: 'home'
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Clean
      # Don't send this alert if it was last triggered less than 30 minutes ago (1,800 seconds)
#      - condition: template
#        value_template: >
#          {% if states.automation.send_alert_when_dishwasher_is_clean.last_triggered is not none %}
#            {% if as_timestamp(now()) | int   -  as_timestamp(states.automation.send_alert_when_dishwasher_is_clean.attributes.last_triggered) | int > 3600 %} true {% else %} false
#            {% endif %}
#          {% else %}
#          false
#          {% endif %}
  action:
    - service: notify.ios_notifier
  #  - service_template: >
  #      {% if (is_state('person.jeroen', 'home')) and (is_state('person.joyce', 'home'))  %}
  #        notify.ios_notifier
  #      {% elif is_state('person.jeroen', 'home') %}
  #        notify.mobile_app_iphone_jeroen
  #      {% elif is_state('person.joyce', 'home') %}
  #        notify.mobile_app_iphone_joyce
  #      {% endif %}
      data:
        message: 'De vaatwasser heeft zijn programma voltooid en kan leeggemaakt worden.'
        title: 'Vaatwasser'
        data:
          push:
            badge: 0
            sound: default
            category: "vaatwasser_alert"