- alias: "Motion: Garage verlichting aan - Licht"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_garage
      to: 'on'
    - platform: state
      entity_id: binary_sensor.contact_garagedeur
      to: 'on'
    - platform: state
      entity_id: binary_sensor.contact_achterdeur
      to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.lux_garage
      above: 30
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: light.garage
        brightness: 50
        # transition: 15

- alias: "Motion: Garage verlichting aan - Donker"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_garage
      to: 'on'
    - platform: state
      entity_id: binary_sensor.contact_garagedeur
      to: 'on'
    - platform: state
      entity_id: binary_sensor.contact_achterdeur
      to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.lux_garage
      below: 30
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: light.garage
        brightness: 100
        # transition: 15


- alias: "Motion: Garage verlichting uit"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_garage
      to: 'off'
      for:
        minutes: 1
  action:
    - service: homeassistant.turn_off
      entity_id: light.garage
      #data:
      #  transition: 160