- alias: "Motion: Slaapkamer vloerled aan"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_slaapkamer
      to: 'on'
  # condition:
  #   condition: time
  #   after: '07:30'
  #   before: '23:30'
  condition:
    condition: and
    conditions:
      - entity_id: sun.sun
        condition: state
        state: 'below_horizon'
      - condition: state
        entity_id: light.ledstrip_slaapkamer
        state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.motion_light_ledstrip_slaapkamer
    - service: light.turn_on
      entity_id: light.ledstrip_slaapkamer
      #data:
      #  transition: 15
      data:
        brightness_pct: 21
        #rgb_color: [255, 255, 255]
        white_value: 100


- alias: "Motion: Slaapkamer vloerled uit"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_slaapkamer
      to: 'off'
      for:
        minutes: 1
  condition:
    - condition: state
      entity_id: input_boolean.motion_light_ledstrip_slaapkamer
      state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.motion_light_ledstrip_slaapkamer
    - service: light.turn_off
      entity_id: light.ledstrip_slaapkamer
      #data:
      #  transition: 160


- alias: Slaapkamer vloerled uit
  trigger:
    - platform: state
      entity_id: light.ledstrip_slaapkamer
      to: 'off'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.motion_light_ledstrip_slaapkamer