- alias: "Notificatie: stroomuitval Tuin"
  initial_state: 'false'
  trigger:
  - platform: state
    entity_id:
      - light.tuin
      - light.terras
      - light.garage
      - light.bijkeuken_leds
      - light.combikast
    to: 'unavailable'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.tuin
        state: 'unavailable'
      - condition: state
        entity_id: light.terras
        state: 'unavailable'
      - condition: state
        entity_id: light.garage
        state: 'unavailable'
      - condition: state
        entity_id: light.bijkeuken_leds
        state: 'unavailable'
      - condition: state
        entity_id: light.combikast
        state: 'unavailable'
  action:
  - service: notify.ios_notifier
    data:
      title: "⚡ Stroomuitval"
      message: "Er is waarschijnlijk stroomuitval in de tuin!"