- alias: "Ulanzi Clock Office: Display off when away"
  id: 5402766f-59f4-4dca-9642-5e3836ced37f
  trigger:
    - platform: state
      entity_id: light.ledctrl_bureau
      from: 'on'
      to: 'off'
      id: ulanzi-office-off
    - platform: state
      entity_id: light.ledctrl_bureau
      from: 'off'
      to: 'on'
      id: ulanzi-office-on
  action:
    - choose:
      - conditions:
        - condition: trigger
          id: ulanzi-office-off
        sequence:
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.matrix
      - conditions:
        - condition: trigger
          id: ulanzi-office-on
        sequence:
          - service: light.turn_on
            data: {}
            target:
              entity_id: light.matrix


- alias: "Ulanzi Clock Office: Notifications"
  id: 0ccc487f-60f1-4e11-bca4-4af18316e1d1
  trigger:
    # - platform: state
    #   entity_id: sensor.envoy_122223030052_current_power_production
    #   id: ulanzi-solarpanels
    # - platform: state
    #   entity_id: sensor.klipper_progress
    #   id: ulanzi-3dprinter
    - platform: state
      entity_id: binary_sensor.doorbell_voordeur
      id: ulanzi-doorbell
    - platform: state
      entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_opening_7
      to: 'on'
      id: ulanzi-garagedoor
    - platform: state
      entity_id: sensor.current_app
      to: 'Time'
      id: ulanzi-kantoor-customapps
  condition: []
  action:
    - choose:
      ## MELDING: DEURBEL
      - conditions:
        - condition: trigger
          id: ulanzi-doorbell
        sequence:
        - service: mqtt.publish
          data:
            topic: ulanzi_kantoor/notify
            payload_template: >-
              {
                "name": "Doorbell",
                "force": true,
                "icon": "51650",
                "moveIcon": false,
                "duration": "60",
                "text": "Ding dong!",
                "color": [ 255, 255, 255 ]
              }
      ## MELDING: GARAGE DOOR
      - conditions:
        - condition: trigger
          id: ulanzi-garagedoor
        sequence:
        - service: mqtt.publish
          data:
            topic: ulanzi_kantoor/notify
            payload_template: >-
              {
                "name": "Garage door",
                "force": true,
                "icon": "42480",
                "moveIcon": false,
                "duration": "60",
                "speed": "800",
                "text": "Garagedeur open",
                "color": [ 255, 255, 255 ]
              }
      - conditions:
        - condition: trigger
          id: ulanzi-kantoor-customapps
        sequence:
        ## APP: SOLAR PANELS
        # - service: mqtt.publish
        #   data:
        #     topic: ulanzi_kantoor/custom/Solarpanels
        #     payload_template: |-
        #       {
        #         "text": '{{states.sensor.envoy_122223030052_current_power_production.state | round(0) }} W',
        #         "icon": "44625",
        #         "pushIcon":0,
        #         "repeat":0,
        #         "textCase":2,
        #         "textOffset":33,
        #         "color": [ 255, 255, 255 ]
        #       }
        ## APP: INTERNET DOWNLOAD
        # - service: mqtt.publish
        #   data:
        #     topic: ulanzi_kantoor/custom/DownloadSpeed
        #     payload_template: |-
        #       {
        #         "text":"Download {{ states.sensor.speedtest_download.state}} Mbp/s",
        #         "icon":"download",
        #         "pushIcon":0,
        #         "repeat":0,
        #         "textCase":2,
        #         "textOffset":33,
        #         "color": [ 255, 255, 255 ]
        #       }
        ## APP: INTERNET UPLOAD
        # - service: mqtt.publish
        #   data:
        #     topic: ulanzi_kantoor/custom/UploadSpeed
        #     payload_template: |-
        #       {
        #         "text":"Upload {{ states.sensor.speedtest_upload.state}} Mbp/s",
        #         "icon":"upload",
        #         "pushIcon":0,
        #         "repeat":0,
        #         "textCase":2,
        #         "textOffset":33,
        #         "color": [ 255, 255, 255 ]
        #       }
  mode: single



- alias: "Ulanzi Clock Office: Enphase solarpanels"
  id: 31b91506-2e10-4bcd-a086-ae9c25014dc9
  use_blueprint:
    path: klumpke/awtrix_enphase_solarpanels.yaml
    input:
      awtrix: 8d57bc2bffdf7e126a42cceada06cb22
      awtrix_app_name: enphase
      production_sensor: sensor.envoy_122223030052_current_power_production
      icon: 44625
      push_icon: "0"
      duration: 10
      repeat: 4


- alias: "Ulanzi Clock Office: 3D Print Status"
  id: 2306e2f5-088e-41c4-b9a8-6cb98db7ebe7
  use_blueprint:
    path: klumpke/awtrix_3dprint_status.yaml
    input:
      awtrix: 8d57bc2bffdf7e126a42cceada06cb22
      awtrix_app_name: 3d_print
      3dprint_progress_sensor: sensor.klipper_progress
      3dprint_current_state_sensor: sensor.klipper_current_print_state
      icon: 51843
      push_icon: "0"
      stack_notification: false
      duration: 10
      repeat: 4


- alias: "Ulanzi Clock Office: Spotify Now Playing"
  id: cfa68846-88da-489d-a47b-a51788d9bbea
  use_blueprint:
    path: klumpke/awtrix_spotify_nowplaying.yaml
    input:
      awtrix: 8d57bc2bffdf7e126a42cceada06cb22
      awtrix_app_name: spotify
      media_player: media_player.spotify_jeroen
      icon: 50252
      push_icon: "0"
      show_rainbow: false
      duration: 10
      repeat: 4


- alias: "Ulanzi Clock Office: DSMR Reader"
  id: 6f3f641f-e98a-478a-857c-6d6d7c0ecb67
  use_blueprint:
    path: klumpke/awtrix_dsmrreader.yaml
    input:
      awtrix:
        - 8d57bc2bffdf7e126a42cceada06cb22
      dsmr_sensor: sensor.power_consumption_watt
      icon: 54077
      push_icon: "0"
      duration: 10
      repeat: 4
      lifetime: 70


- alias: "Ulanzi Clock Office: EV Charger"
  id: b5077fef-a67c-49df-b3e0-e0f7721285f5
  use_blueprint:
    path: klumpke/awtrix_ev_charger.yaml
    input:
      awtrix: 8d57bc2bffdf7e126a42cceada06cb22
      awtrix_app_name: ev_charger
      ev_sensor: sensor.alfen_active_power_total_socket_1
      icon: 44231
      push_icon: "0"
      duration: 10
      repeat: 4