- alias: "3D Printer: Notify, 3D print is ready"
  trigger:
    - platform: state
      entity_id: binary_sensor.octoprint_printing
      from: "on"
      to: "off"
  action:
    - service: notify.mobile_app_iklumpke
      data:
        title: "3D Printer"
        message: "Je 3D print is klaar"
        data:
          attachment:
            url: !secret http_camera_3dprinter
            content-type: jpeg
            hide-thumbnail: false

- alias: "3D Printer: Take screenshot at 100%"
  trigger:
    - platform: state
      entity_id: sensor.octoprint_print_progress
      to: '100'
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.octoprint
        filename: "/config/www/images/snapshots/cam_3dprinter.jpg"

- alias: "3D Printer: Power on LEDs when print is started."
  trigger:
    - platform: state
      entity_id: binary_sensor.octoprint_printing
      to: "on"
  action:
    - service: shell_command.octoprint_light_on


- alias: "3D Printer: Power off 3D printer when finished."
  trigger:
    - platform: state
      entity_id: binary_sensor.octoprint_printing
      to: "off"
      for:
        minutes: 15
  action:
    - service: switch.turn_off
      entity_id: switch.3d_printer

    - service: shell_command.octoprint_light_off