- alias: "Notificatie: Open zolderraam bij regenval"
  initial_state: 'false'
  trigger:
  - entity_id: sensor.yr_symbol
    platform: state
    to: '9'
  - entity_id: sensor.yr_symbol
    platform: state
    to: '10'
  - entity_id: sensor.yr_symbol
    platform: state
    to: '30'
  - entity_id: sensor.yr_symbol
    platform: state
    to: '40'
  - entity_id: sensor.yr_symbol
    platform: state
    to: '46'
  condition:
  - entity_id: binary_sensor.contact_zolderraam
    state: 'on'
    condition: state
  action:
  - service: notify.ios_notifier
    data:
      title: "🪟 Zolderraam open"
      message: "Het regent en het zolderraam staat nog open!"