- alias: "Notificatie: Open zolderraam bij regenval"
  trigger:
    - entity_id: sensor.yr_symbol
      platform: state
      to: "rain"
    - entity_id: sensor.yr_symbol
      platform: state
      to: "heavyrain"
    - entity_id: sensor.yr_symbol
      platform: state
      to: "lightrain"
  # - entity_id: sensor.yr_symbol
  #   platform: state
  #   to: 'rainshowers_day'
  # - entity_id: sensor.yr_symbol
  #   platform: state
  #   to: 'lightrainshowers_day'

  condition:
    - entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_opening_3
      state: "on"
      condition: state
  action:
    - service: notify.ios_notifier
      data:
        title: "🪟 Zolderraam open"
        message: "Het regent en het zolderraam staat nog open!"
