- alias: "Notificatie: Afvalwijzer"
  trigger:
    platform: time
    at: '20:00:00'
  condition:
    - condition: template
      value_template: "{{ states('sensor.blink_morgen') != 'Geen' }}"
  action:
  - service: notify.ios_notifier
    data:
      title: "Afvalwijzer"
      message: ' Afvaltype(n): {{ states.sensor.blink_morgen.state }} wordt morgen opgehaald!'
      data:
        url: /dwains-dashboard/more_page_addon_afvalwijzer

- alias: "Notificatie Dwains Dashboard: Afvalwijzer morgen"
  description: 'This automation creates a notification in Dwains theme'
  trigger:
  - at: '00:01'
    platform: time
  condition:
    - condition: template
      value_template: "{{ states('sensor.blink_morgen') != 'Geen' }}"
  action:
  - service: dwains_dashboard.notification_create
    data:
      message: "{{ states.sensor.blink_morgen.state }} wordt morgen opgehaald."
      notification_id: garbage

- alias: "Notificatie Dwains Dashboard: Afvalwijzer vandaag"
  description: 'This automation edits the previous notification in Dwains theme'
  trigger:
  - at: '00:01'
    platform: time
  condition:
    - condition: template
      value_template: "{{ states('sensor.blink_vandaag') != 'Geen' }}"
  action:
  - service: dwains_dashboard.notification_create
    data:
      message: "{{ states.sensor.blink_vandaag.state }} wordt vandaag opgehaald."
      notification_id: garbage

- alias: "Notificatie Dwains Dashboard: Afvalwijzer verwijder melding"
  description: 'This automation dismisses the garbage notification in Dwains theme'
  trigger:
  - at: '23:59'
    platform: time
  condition:
    - condition: template
      value_template: "{{ states('sensor.blink_vandaag') != 'Geen' }}"
  action:
  - service: dwains_dashboard.notification_dismiss
    data:
      notification_id: garbage