---
# VERSTUUR NOTIFICATIE + SNAPSHOT WANNEER ER WORDT AANGEBELD
- id: deurbel
  alias: "Notificatie: Deurbel snapshot"
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.doorbell_voordeur
    from: 'off'
    to: 'on'
  # condition:
  # ### dit voorkomt het klapperen
  #   condition: template
  #   value_template: '{{ (as_timestamp(now()) - as_timestamp(states.automation.notificatie_deurbel_snapshot.attributes.last_triggered | default(0)) | int > 10)}}'
  action:
  - service: camera.snapshot
    data:
      entity_id: camera.voordeur
      filename: "/config/www/images/snapshots/cam_voordeur.jpg"
  # - service: notify.ios_notifier
  #   data:
  #     title: "Deurbel"
  #     message: "Er is aangebeld!"
  #     data:
  #       attachment:
  #         url: !secret http_camera_voordeur
  #         content-type: jpeg
  #         hide-thumbnail: false
  #       actions:
  #         - action: URI
  #           title: View in HA
  #           uri: dwains-dashboard/more_page_addon_camera_s
  #         - action: URI
  #           title: View in Protect
  #           uri: 'app://com.ubnt.unifi.protect'
  - service: notify.pushover
    data:
      title: "🔔 Deurbel"
      message: "Er is aangebeld!"
      data:
        sound: pushover
        attachment: "/config/www/images/snapshots/cam_voordeur.jpg"
  - service: notify.tv_woonkamer
    data:
      title: "🔔  Deurbel"
      message: "Er is aangebeld!"
      data:
        fontsize: small
        position: top-right
        duration: 10
        interrupt: true
        file:
          path: "/config/www/images/snapshots/cam_voordeur.jpg"
  - service: notify.tv_slaapkamer
    data:
      title: "🔔  Deurbel"
      message: "Er is aangebeld!"
      data:
        fontsize: small
        position: top-right
        duration: 10
        interrupt: true
        file:
          path: "/config/www/images/snapshots/cam_voordeur.jpg"

- alias: "Notificatie: Deurbel audio"
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.doorbell_voordeur
    from: 'off'
    to: 'on'
  action:
  - service: script.sonos_play
    data:
      sonos_entity: media_player.eetkamer, media_player.boven, media_player.zolder, media_player.tuin
      volume: 0.4
      media_content: !secret http_audio_deurbel
      delay: '00:00:03'

- alias: "Notificatie: Deurbel stream"
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.doorbell_voordeur
    from: 'off'
    to: 'on'
  action:
  - service: media_player.volume_mute
    data:
      entity_id: media_player.hub_keuken
      is_volume_muted: true
  - service: camera.play_stream
    data:
      entity_id: camera.voordeur
      media_player: media_player.hub_keuken
  - delay: "00:02:00"
  - service: media_player.turn_off
    data:
      entity_id: media_player.hub_keuken