- alias: "Ulanzi Clock Livingroom: Display off when away"
  id: 834a6818-7553-42a5-bb2b-144566f275a2
  trigger:
    - platform: state
      entity_id: group.device_status
      from: 'home'
      to: 'not_home'
      id: ulanzi-livingroom-off
    - platform: state
      entity_id: group.device_status
      from: 'not_home'
      to: 'home'
      id: ulanzi-livingroom-on
  action:
    - choose:
      - conditions:
        - condition: trigger
          id: ulanzi-livingroom-off
        sequence:
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.matrix_2
      - conditions:
        - condition: trigger
          id: ulanzi-livingroom-on
        sequence:
          - service: light.turn_on
            data: {}
            target:
              entity_id: light.matrix_2


- alias: "Ulanzi Clock Livingroom: Notifications"
  id: 0fd58034-4101-471b-a38e-012bb06c9214
  trigger:
    - platform: state
      entity_id: binary_sensor.doorbell_voordeur
      id: ulanzi-doorbell
    - platform: state
      entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_opening_7
      to: 'on'
      id: ulanzi-garagedoor
  condition: []
  action:
    - choose:
      ## MELDING: DEURBEL
      - conditions:
        - condition: trigger
          id: ulanzi-doorbell
        sequence:
        - service: mqtt.publish
          data:
            topic: ulanzi_woonkamer/notify
            payload_template: >-
              {
                "name": "Doorbell",
                "force": true,
                "icon": "51650",
                "moveIcon": false,
                "duration": "60",
                "text": "Ding dong!",
                "color": [ 255, 255, 255 ]
              }
      ## MELDING: GARAGE DOOR
      - conditions:
        - condition: trigger
          id: ulanzi-garagedoor
        sequence:
        - service: mqtt.publish
          data:
            topic: ulanzi_woonkamer/notify
            payload_template: >-
              {
                "name": "Garage door",
                "force": true,
                "icon": "42480",
                "moveIcon": false,
                "duration": "60",
                "speed": "800",
                "text": "Garagedeur open",
                "color": [ 255, 255, 255 ]
              }
  mode: single


- alias: "Ulanzi Clock Livingroom: Enphase solarpanels"
  id: afe130cf-2c4a-48ed-8e68-f63720d80eea
  use_blueprint:
    path: klumpke/awtrix_enphase_solarpanels.yaml
    input:
      awtrix: 37cfe14ac1655af3ab082feb6a569a92
      awtrix_app_name: enphase
      production_sensor: sensor.envoy_122223030052_current_power_production
      icon: 44625
      push_icon: "0"
      duration: 10
      repeat: 4


- alias: "Ulanzi Clock Livingroom: 3D Print Status"
  id: dd820500-e22c-461a-8084-4ec5b6bcf146
  use_blueprint:
    path: klumpke/awtrix_3dprint_status.yaml
    input:
      awtrix: 37cfe14ac1655af3ab082feb6a569a92
      awtrix_app_name: 3d_print
      3dprint_progress_sensor: sensor.klipper_progress
      3dprint_current_state_sensor: sensor.klipper_current_print_state
      icon: 51843
      push_icon: "0"
      stack_notification: false
      duration: 10
      repeat: 4


- alias: "Ulanzi Clock Livingroom: Spotify Now Playing"
  id: 06293da3-5bcd-4955-8b52-04ba5327b439
  use_blueprint:
    path: klumpke/awtrix_spotify_nowplaying.yaml
    input:
      awtrix: 37cfe14ac1655af3ab082feb6a569a92
      awtrix_app_name: spotify
      media_player: media_player.spotify_jeroen
      icon: 50252
      push_icon: "0"
      duration: 10
      repeat: 4


- alias: "Ulanzi Clock Livingroom: DSMR Reader"
  id: 0e246c20-9944-4046-9ae8-548bd074c412
  use_blueprint:
    path: klumpke/awtrix_dsmrreader.yaml
    input:
      awtrix:
        - 37cfe14ac1655af3ab082feb6a569a92
      dsmr_sensor: sensor.power_consumption_watt
      icon: 54077
      push_icon: "0"
      duration: 10
      repeat: 4
      lifetime: 70


- alias: "Ulanzi Clock Office: EV Charger"
  id: 0a294206-b4ec-4c8e-a6ae-0f8563ce1dd4
  use_blueprint:
    path: klumpke/awtrix_ev_charger.yaml
    input:
      awtrix: 37cfe14ac1655af3ab082feb6a569a92
      awtrix_app_name: ev_charger
      ev_sensor: sensor.alfen_active_power_total_socket_1
      icon: 44231
      push_icon: "0"
      duration: 10
      repeat: 4