- alias: "iOS Actionable Notificatie: Sonos"
  initial_state: true
  trigger:
  - platform: state
    entity_id: group.device_status
    from: 'home'
    to: 'not_home'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: 'media_player.woonkamer'
      state: 'playing'
    - condition: state
      entity_id: 'media_player.eetkamer'
      state: 'playing'
    - condition: state
      entity_id: 'media_player.boven'
      state: 'playing'
    - condition: state
      entity_id: 'media_player.zolder'
      state: 'playing'
    - condition: state
      entity_id: 'media_player.tuin'
      state: 'playing'
  action:
  - service: notify.mobile_app_iklumpke
    data:
      title: "🔊 Sonos"
      message: "Let op, speakers staan nog aan"
      data:
        actions:
          - action: "SONOS_UITSCHAKELEN"
            title: "Uitschakelen"
          - action: 'SONOS_ANNULEREN'
            title: 'Annuleren'
            destructive: true


- alias: "iOS Actionable Notificatie: Sonos uitschakelen"
  trigger:
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: "SONOS_UITSCHAKELEN"
  action:
    service: media_player.media_stop
    entity_id: media_player.woonkamer, media_player.eetkamer, media_player.boven, media_player.zolder, media_player.tuin