---
# VERSTUUR NOTIFICATIE + SNAPSHOT WANNEER ER WORDT AANGEBELD
- id: deurbel
  alias: "Notificatie: Deurbel snapshot"
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.doorbell_voordeur
    from: 'off'
    to: 'on'
  # condition:
  # ### dit voorkomt het klapperen
  #   condition: template
  #   value_template: '{{ (as_timestamp(now()) - as_timestamp(states.automation.notificatie_deurbel_snapshot.attributes.last_triggered | default(0)) | int > 10)}}'
  action:
  - service: camera.snapshot
    data:
      entity_id: camera.voordeur
      filename: "/config/www/images/snapshots/cam_voordeur.jpg"
  # - service: notify.ios_notifier
  #   data:
  #     title: "Deurbel"
  #     message: "Er is aangebeld!"
  #     data:
  #       attachment:
  #         url: !secret http_camera_voordeur
  #         content-type: jpeg
  #         hide-thumbnail: false
  #       actions:
  #         - action: URI
  #           title: View in HA
  #           uri: dwains-dashboard/more_page_addon_camera_s
  #         - action: URI
  #           title: View in Protect
  #           uri: 'app://com.ubnt.unifi.protect'
  - service: notify.pushover
    data:
      title: "🔔 Deurbel"
      message: "Er is aangebeld!"
      data:
        sound: pushover
        attachment: "/config/www/images/snapshots/cam_voordeur.jpg"
  # - service: notify.tv_woonkamer
  #   data:
  #     title: "🔔  Deurbel"
  #     message: "Er is aangebeld!"
  #     data:
  #       fontsize: small
  #       position: top-right
  #       duration: 10
  #       interrupt: true
  #       file:
  #         path: "/config/www/images/snapshots/cam_voordeur.jpg"
  # - service: notify.tv_slaapkamer
  #   data:
  #     title: "🔔  Deurbel"
  #     message: "Er is aangebeld!"
  #     data:
  #       fontsize: small
  #       position: top-right
  #       duration: 10
  #       interrupt: true
  #       file:
  #         path: "/config/www/images/snapshots/cam_voordeur.jpg"


- alias: "Notificatie: Deurbel audio"
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.doorbell_voordeur
    from: 'off'
    to: 'on'
  action:
  # - service: script.sonos_play
  #   data:
  #     sonos_entity:
  #       - media_player.eetkamer
  #       - media_player.boven
  #       - media_player.zolder
  #       - media_player.tuin
  #     volume: 0.4
  #     media_content: !secret http_audio_deurbel
  #     delay: '00:00:03'
  - service: media_player.play_media
    data:
      entity_id:
        - media_player.woonkamer_sonos_cloud
        - media_player.eetkamer_sonos_cloud
        - media_player.kantoor_sonos_cloud
        - media_player.zolder_sonos_cloud
        - media_player.tuin_sonos_cloud
      media_content_id: !secret http_audio_deurbel
      media_content_type: music
      extra:
        volume: 20


- alias: "Notificatie: Deurbel stream"
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.doorbell_voordeur
    from: 'off'
    to: 'on'
  action:
  - service: media_player.volume_mute
    data:
      entity_id: media_player.hub_keuken
      is_volume_muted: true
  - service: camera.play_stream
    data:
      entity_id: camera.voordeur
      media_player: media_player.hub_keuken
  - delay: "00:02:00"
  - service: media_player.turn_off
    data:
      entity_id: media_player.hub_keuken


- alias: "Deurbel: Bericht op display"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_voordeur
      to: person
      attribute: event_object
    # - platform: template
    #   value_template: "{{ as_timestamp(now()) - as_timestamp(state_attr('binary_sensor.motion_voordeur', 'last_tripped_time')) < 10 }}"
    - platform: state
      entity_id: binary_sensor.doorbell_voordeur
      from: "off"
      to: "on"
    # - platform: template
    #   value_template: "{{ as_timestamp(now()) - as_timestamp(state_attr('binary_sensor.doorbell_voordeur', 'last_tripped_time')) < 10 }}"
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.doorbell_voordeur
              state: "on"
            # - condition: template
            #   value_template: "{{ as_timestamp(now()) - as_timestamp(state_attr('binary_sensor.doorbell_voordeur', 'last_tripped_time')) < 10 }}"
            - condition: state
              entity_id: group.device_status
              state: "home"
            # - condition: state
            #   entity_id: binary_sensor.voordeur
            #   state: "off"
          sequence:
            - service: text.set_value
              target:
                entity_id: text.voordeur_doorbell
              data:
                value: "MOMENTJE..."
        - conditions:
            - condition: time
              after: "06:00:00"
              before: "12:00:00"
          sequence:
            - service: text.set_value
              target:
                entity_id: text.voordeur_doorbell
              data:
                value: "GOEDEMORGEN"
        - conditions:
            - condition: time
              after: "12:00:00"
              before: "17:30:00"
          sequence:
            - service: text.set_value
              target:
                entity_id: text.voordeur_doorbell
              data:
                value: "GOEDEMIDDAG"
        - conditions:
            - condition: time
              after: "17:30:00"
              before: "23:59:00"
          sequence:
            - service: text.set_value
              target:
                entity_id: text.voordeur_doorbell
              data:
                value: "GOEDENAVOND"
        - conditions:
            - condition: time
              after: "00:00:00"
              before: "06:00:00"
          sequence:
            - service: text.set_value
              target:
                entity_id: text.voordeur_doorbell
              data:
                value: "GOEDENACHT"
      default:
            - service: text.set_value
              target:
                entity_id: text.voordeur_doorbell
              data:
                value: "WELKOM"