---
# VERSTUUR NOTIFICATIE + SNAPSHOT WANNEER ER WORDT AANGEBELD
- id: deurbel
  alias: "Notificatie: Deurbel"
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.deurbel_knop
    from: 'off'
    to: 'on'
  # condition:
  # ### dit voorkomt het klapperen
  #   condition: template
  #   value_template: '{{ (as_timestamp(now()) - as_timestamp(states.automation.automation_notify_doorbell.attributes.last_triggered | default(0)) | int > 10)}}'
  action:
  - service: camera.snapshot
    data:
      entity_id: camera.voordeur
      filename: '/config/www/images/snapshots/cam_voordeur.jpg'
  - service: notify.ios_notifier
    data:
      title: "Deurbel"
      message: "Er is aangebeld!"
      data:
        attachment:
          url: "https://hass.klompen.net/local/images/snapshots/cam_voordeur.jpg"
          content-type: jpeg
          hide-thumbnail: false
#  - service: notify.pushover
#    data:
#      title: "Deurbel"
#      message: "Er is aangebeld!"
#      data:
#        attachment: "https://hass.klompen.net/local/images/snapshots/cam_voordeur.jpg"
  - service: camera.play_stream
    data:
      entity_id: camera.voordeur_2
      media_player: media_player.hub_keuken
  - service: script.sonos_play
    data:
      sonos_entity: media_player.woonkamer, media_player.eetkamer, media_player.boven, media_player.tuin
      volume: 0.4
      media_content: "https://hass.klompen.net/local/audio/deurbel.mp3"
      delay: '00:00:03'
  - delay: "00:00:30"
  - service: media_player.turn_off
    data:
      entity_id: media_player.hub_keuken


# Deurbel aan na 8.00u
# Deurbel uit na 22.00u
#
- alias: "Deurbel AAN na 07.30u"
  trigger:
    platform: time
    at: "07:30:00"
  action:
    service: switch.turn_on
    entity_id: switch.deurbel_bel_actief

- alias: "Deurbel UIT na 22.00u"
  trigger:
    platform: time
    at: "22:00:00"
  action:
    service: switch.turn_off
    entity_id: switch.deurbel_bel_actief