- alias: "Notificatie: Afvalwijzer"
  trigger:
    platform: time
    at: '20:00:00'
  condition:
    - condition: template
      value_template: "{{ states('sensor.blink_morgen') != 'Geen' }}"
  action:
  - service: notify.ios_notifier
    data:
      title: "♻️ Afvalwijzer"
      message: 'Afvaltype(n): {{ states.sensor.blink_morgen.state }} wordt morgen opgehaald!'
      data:
        url: /lovelace-klompen/page_afvalwijzer