# - alias: "auto_pump_on enabled"
#   trigger:
#     platform: state
#     entity_id: input_slider.auto_pump_minutes, input_slider.auto_pump_duration
#   action:
#   - service: homeassistant.turn_on
#     data:
#       entity_id:
#         - automation.auto_pump_on
#   - service: homeassistant.turn_on
#     data:
#       entity_id:
#         - automation.auto_pump_off

# - alias: 'auto_pump![Pool Pump slider|690x354](//community-home-assistant-assets.s3-us-west-2.amazonaws.com/original/2X/7/70ce0352bf985503fe4ed0fc4f77aa4115b0d72f.png)_on'
#   initial_state: True
#   trigger:
#     - platform: time
#       minutes: '/1'
#       seconds: 10
#   condition:
#     - condition: template
#       value_template: '{{ (now().strftime("%s") | int | timestamp_custom("%H:%M")) == states.sensor.auto_pump_start.state }}'
#   action:
#     - service: homeassistant.turn_on
#       entity_id: "group.Pool"

# - alias: 'auto_pump_off'
#   initial_state: True
#   trigger:
#     - platform: time
#       minutes: '/1'
#       seconds: 10
#   condition:
#     - condition: template
#       value_template: '{{ (now().strftime("%s") | int | timestamp_custom("%H:%M")) == states.sensor.auto_pump_stop.state }}'
#   action:
#     - service: homeassistant.turn_off
#       entity_id: "group.Pool"


- alias: "Zwembadpomp: zet aan"
  trigger:
    - platform: state
      entity_id: input_select.pool_pump
      to: 'Aan'
  action:
    service: homeassistant.turn_on
    entity_id: switch.zwembadpomp

- alias: "Zwembadpomp: zet uit"
  trigger:
    - platform: state
      entity_id: input_select.pool_pump
      to: 'Uit'
  action:
    service: homeassistant.turn_off
    entity_id: switch.zwembadpomp

## Checks pool pump status every few minutes defined by minutes: '/6' (6 minutes in this case)
## and as long as the Input slider is set to Auto, the swimming season has been turned on
## and it's between 0800 and 1655, it will turn the pump on. Designed without timers to
## survive HA restarts ##
- alias: "Zwembadpomp: Check pomp in seizoen"
  trigger:
    - platform: time_pattern
      minutes: '/6'
      seconds: 00
  condition:
    - condition: time
      after: '08:00:00'
      before: '16:55:00'
    - condition: state
      entity_id: input_select.pool_pump
      state: Auto
    - condition: state
      entity_id: input_boolean.swimming_season
      state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.zwembadpomp

- alias: "Zwembadpomp: Check pomp buiten seizoen"
  trigger:
      - platform: time_pattern
        minutes: '/6'
        seconds: 00
  condition:
        - condition: time
          after: '08:00:00'
          before: '11:55:00'
        - condition: state
          entity_id: input_select.pool_pump
          state: Auto
        - condition: state
          entity_id: input_boolean.swimming_season
          state: 'off'
  action:
      service: homeassistant.turn_on
      entity_id: switch.zwembadpomp

- alias: "Zwembadpomp: Pomp uit om 17.00u"
  trigger:
    platform: time
    at: '17:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.swimming_season
      state: 'on'
    - condition: state
      entity_id: input_select.pool_pump
      state: Auto
  action:
    service: homeassistant.turn_off
    entity_id: switch.zwembadpomp

- alias: "Zwembadpomp: Pomp uit om 12.00u"
  trigger:
    platform: time
    at: '12:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.swimming_season
      state: 'off'
    - condition: state
      entity_id: input_select.pool_pump
      state: Auto
  action:
    service: homeassistant.turn_off
    entity_id: switch.zwembadpomp