- alias: 'Systeem: Backup wekelijks'
  trigger:
    platform: time
    at: '03:00:00'
  condition:
    condition: time
    weekday:
      - sun
  action:
    - service: auto_backup.backup_full
      data:
        name: Home Assistant weekly {{now().strftime('%Y-%m-%d')}}
        keep_days: 30
        exclude:
          # addons:
          #   - Portainer
          folders:
            - share
            - media

- alias: "Notificatie: Backup mislukt"
  trigger:
    platform: event
    event_type: auto_backup.backup_failed
  action:
    - service: notify.mobile_app_iklumpke
      data:
        title: "🚧 Backup mislukt"
        message: "Naam: {{ trigger.event.data.name }}\nFout: {{ trigger.event.data.error }}"