substitutions:
  # used internally
  device_name: 'ctrl_swimmingpool'
  # displayed in HA
  friendly_name: 'Controller Zwembad'

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${friendly_name}
    password: !secret wifi_pass

captive_portal:

# Enable Web
web_server:
  port: 80

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_pass

ota:
  password: !secret ota_pass

# Dallas sensor
dallas:
  - pin: GPIO5
    update_interval: 10s

# Sensors
sensor:
  - platform: dallas
    address: 0xB900000C23572928
    name: "Zwembad Temperatuur"