substitutions:
  # used internally
  device_name: 'ledctrl_slaapkamer'
  # displayed in HA
  friendly_name: 'Ledstrip Slaapkamer'

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${friendly_name}
    password: !secret wifi_pass

captive_portal:

# Enable Web
web_server:
  port: 80

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_pass

ota:
  password: !secret ota_pass

light:
  - platform: rgbw
    name: "${friendly_name}"
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    white: pwm_w
    #default_transition_length: 2s
    effects:
      - random:
      - strobe:
      - flicker:
#light:
#  - platform: rgb
#    name: "RGB"
#    red: pwm_r
#    green: pwm_g
#    blue: pwm_b
#  - platform: monochromatic
#    name: "Wit"
#    output: pwm_w

output:
  - platform: esp8266_pwm
    pin: GPIO04
    id: pwm_r
  - platform: esp8266_pwm
    pin: GPIO12
    id: pwm_g
  - platform: esp8266_pwm
    pin: GPIO14
    id: pwm_b
  - platform: esp8266_pwm
    pin: GPIO13
    id: pwm_w