substitutions:
  # used internally
  device_name: 'ledstrip_slaapkamer'
  # displayed in HA
  friendly_name: 'Ledstrip Slaapkamer'

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

# Enable Web
web_server:
  port: 80

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_pass

ota:
  password: !secret ota_pass

output:
  - platform: esp8266_pwm
    pin: GPIO04
    id: 'color_red'
  - platform: esp8266_pwm
    pin: GPIO12
    id: 'color_green'
  - platform: esp8266_pwm
    pin: GPIO14
    id: 'color_blue'
  - platform: esp8266_pwm
    pin: GPIO13
    id: 'color_white'
    
light:
  - platform: rgbw
    name: "${friendly_name}"
    white: color_white
    red: color_red
    green: color_green
    blue: color_blue
    #default_transition_length: 2s
    effects:
      - random:
      - strobe:
      - flicker: