substitutions:
  plug_name: socket_shp2_flex
# only change upper plug_name and plug_ip
# put a secret.yaml file in the map with switchbw_6.yaml
  current_res: "0.00221"
  voltage_div: "955"

esphome:
  name: ${plug_name}
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

# Enable Web
web_server:
  port: 80

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_pass

ota:
  password: !secret ota_pass

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: gpio
    name: ${plug_name}_button
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay
  - platform: status
    name: ${plug_name}_Status

switch:
  - platform: gpio
    id: relay
    name: ${plug_name}_Relay
    icon: mdi:power-socket-eu
    restore_mode: ALWAYS_ON
    pin: GPIO14
    on_turn_on:
      - switch.turn_on: blue_led
    on_turn_off:
      - switch.turn_off: blue_led

  - platform: gpio
    id: blue_led
    name: ${plug_name}_LED_Blue
    icon: mdi:led-on
    restore_mode: ALWAYS_ON
    pin:
      number: GPIO1
      inverted: True

  - platform: gpio
    id: red_led
    name: ${plug_name}_LED_Red
    icon: mdi:led-on
    restore_mode: ALWAYS_OFF
    pin:
      number: GPIO13
      inverted: True

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      name: ${plug_name}_Amperage
      icon: mdi:current-ac
      unit_of_measurement: A
    voltage:
      name: ${plug_name}_Voltage
      icon: mdi:flash-circle
      unit_of_measurement: V
    power:
      name: ${plug_name}_Wattage
      icon: mdi:flash-outline
      unit_of_measurement: W
      id: ${plug_name}_Wattage
    change_mode_every: 8
    update_interval: 10s

  - platform: total_daily_energy
    name: ${plug_name}_Total Daily Energy
    icon: mdi:circle-slice-3
    power_id: ${plug_name}_Wattage
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh

# Extra sensor to keep track of plug uptime
  - platform: uptime
    name: ${plug_name}_Uptime_Sensor

  - platform: wifi_signal
    name: ${plug_name}_Wi-Fi_Signal
    update_interval: 60s

text_sensor:
  - platform: version
    name: ${plug_name}_firmware_version